// Renders data/lab.json (generated by scripts/build-data.mjs). Model artifacts are shown as-is.
const VIEWPORTS = {
  desktop: { label: "桌面", width: 1440, height: 900 },
  mobile: { label: "手机", width: 390, height: 844 }
};

const app = document.querySelector("#app");
let lab = null;
let lastPage = null;
let pendingFocus = null;
const frameObserver = new ResizeObserver((entries) => entries.forEach((entry) => fitFrame(entry.target)));

const escapeHtml = (value) => String(value ?? "").replace(/[&<>"']/g, (char) => (
  { "&": "&amp;", "<": "&lt;", ">": "&gt;", "\"": "&quot;", "'": "&#39;" }[char]
));

function parseRoute() {
  const raw = location.hash.replace(/^#\/?/, "");
  const [path, query = ""] = raw.split("?");
  return { path: decodeURIComponent(path), params: new URLSearchParams(query) };
}

function experimentHash(experiment, params = {}) {
  const query = new URLSearchParams(Object.entries(params).filter(([, value]) => value));
  const text = query.toString();
  return `#/${experiment.id}${text ? `?${text}` : ""}`;
}

function navigate(hash, { replace = false } = {}) {
  if (replace) {
    history.replaceState(null, "", hash);
    render();
  } else {
    location.hash = hash;
  }
}

function vendorLabel(vendor) {
  return lab.vendors[vendor]?.label ?? vendor;
}

function vendorDot(vendor) {
  return `<span class="vendor-dot" data-vendor="${escapeHtml(vendor)}" aria-hidden="true"></span>`;
}

function scoreText(result) {
  return result.score ? String(result.score.total) : "待评";
}

function scoredResults(experiment) {
  return experiment.results.filter((result) => result.score);
}

/* ---------- Home ---------- */

function renderHome(params) {
  const experiments = lab.experiments;
  const totalResults = experiments.reduce((sum, experiment) => sum + experiment.results.length, 0);
  const models = new Map();
  experiments.forEach((experiment) => experiment.results.forEach((result) => {
    if (!models.has(result.model)) models.set(result.model, { model: result.model, label: result.label.replace(/ · Run \d+$/, ""), vendor: result.vendor });
  }));
  const modelRows = [...models.values()].sort((a, b) =>
    vendorLabel(a.vendor).localeCompare(vendorLabel(b.vendor)) || a.label.localeCompare(b.label));

  document.title = "LLM Capability Lab · 大模型能力实验台";
  app.innerHTML = `
    <section class="hero">
      <p class="eyebrow">大模型能力实验台</p>
      <h1>同一份 Prompt，看不同模型各自做出了什么</h1>
      <p class="hero-lead">每个实验只给模型同一段输入，产物原样保存、不做修改。你可以直接打开结果，并排比较，再对照评分看差距在哪。</p>
      <dl class="stat-row">
        <div class="stat"><dt>实验</dt><dd>${experiments.length}</dd></div>
        <div class="stat"><dt>模型</dt><dd>${models.size}</dd></div>
        <div class="stat"><dt>产物</dt><dd>${totalResults}</dd></div>
        <div class="stat"><dt>已评分</dt><dd>${experiments.reduce((sum, experiment) => sum + scoredResults(experiment).length, 0)}</dd></div>
      </dl>
    </section>

    <section class="section" aria-labelledby="experiments-heading">
      <div class="section-head">
        <h2 id="experiments-heading">全部实验</h2>
        <p>每个实验考察一种能力，点进去看 Prompt 和所有模型的产物。</p>
      </div>
      <div class="experiment-grid">
        ${experiments.map(renderExperimentCard).join("")}
      </div>
    </section>

    <section class="section" id="matrix" aria-labelledby="matrix-heading">
      <div class="section-head">
        <h2 id="matrix-heading">模型 × 实验</h2>
        <p>格子里是该实验内的得分（满分 100）。分数只在同一实验里可比，所以不算跨实验总分。</p>
      </div>
      <div class="matrix-scroll" tabindex="0" role="region" aria-label="模型与实验得分对照表，可横向滚动">
        <table class="matrix">
          <thead>
            <tr>
              <th scope="col" class="matrix-model">模型</th>
              ${experiments.map((experiment) => `
                <th scope="col"><a href="${experimentHash(experiment)}"><span class="mono">${experiment.number}</span> ${escapeHtml(experiment.title)}</a></th>`).join("")}
            </tr>
          </thead>
          <tbody>
            ${modelRows.map((row) => `
              <tr>
                <th scope="row" class="matrix-model">
                  <span class="model-name">${vendorDot(row.vendor)}${escapeHtml(row.label)}</span>
                  <span class="model-vendor">${escapeHtml(vendorLabel(row.vendor))}</span>
                </th>
                ${experiments.map((experiment) => renderMatrixCell(experiment, row.model)).join("")}
              </tr>`).join("")}
          </tbody>
        </table>
      </div>
      <p class="matrix-legend"><span class="cell-pending">待评</span> 已有产物，还没评分　<span class="cell-empty">—</span> 没有参加这个实验</p>
    </section>
  `;

  if (params.get("section") === "matrix") requestAnimationFrame(() => document.querySelector("#matrix")?.scrollIntoView());
}

function renderExperimentCard(experiment) {
  const scored = scoredResults(experiment);
  const top = scored[0];
  const thumb = experiment.thumb
    ? `<img src="${escapeHtml(experiment.thumb)}" alt="" loading="lazy" width="720" height="450">`
    : `<span class="thumb-placeholder mono">${experiment.number}</span>`;
  return `
    <a class="experiment-card" href="${experimentHash(experiment)}">
      <div class="card-thumb${experiment.artifactType === "image" ? " is-image" : ""}">${thumb}</div>
      <div class="card-body">
        <div class="card-meta"><span class="mono">${experiment.number}</span><span class="tag">${escapeHtml(experiment.capability)}</span></div>
        <h3>${escapeHtml(experiment.title)}</h3>
        <p>${escapeHtml(experiment.question)}</p>
      </div>
      <div class="card-foot">
        <span>${experiment.results.length} 份产物 · 已评 ${scored.length}</span>
        ${top ? `<span class="card-top">${vendorDot(top.vendor)}${escapeHtml(top.label)} <strong>${top.score.total}</strong></span>` : `<span class="muted">尚未评分</span>`}
      </div>
    </a>`;
}

function renderMatrixCell(experiment, model) {
  const results = experiment.results.filter((result) => result.model === model);
  if (!results.length) return `<td><span class="cell-empty" aria-label="未参加">—</span></td>`;
  const best = results.find((result) => result.score) ?? results[0];
  const href = experimentHash(experiment, { m: best.key });
  if (!best.score) return `<td><a class="cell-pending" href="${href}">待评</a></td>`;
  const scored = scoredResults(experiment);
  const isTop = scored[0]?.key === best.key && scored.length > 1;
  return `<td><a class="cell-score${isTop ? " is-top" : ""}" href="${href}" title="${escapeHtml(experiment.title)}：${best.score.total} / 100${isTop ? "（本实验最高）" : ""}">
    <span class="cell-bar" style="--value:${best.score.total}" aria-hidden="true"></span><strong>${best.score.total}</strong></a></td>`;
}

/* ---------- Experiment ---------- */

function renderExperiment(experiment, params) {
  const results = experiment.results;
  const active = results.find((result) => result.key === params.get("m")) ?? results[0] ?? null;
  const view = params.get("view") === "compare" && results.length > 1 ? "compare" : "focus";
  const isPage = experiment.artifactType === "page";
  const viewport = isPage && params.get("vp") === "mobile" ? "mobile" : "desktop";
  const state = { m: active?.key, view: view === "compare" ? "compare" : null, vp: viewport === "mobile" ? "mobile" : null };
  const link = (changes) => experimentHash(experiment, { ...state, ...changes });

  document.title = `${experiment.number} ${experiment.title} · LLM Capability Lab`;
  app.innerHTML = `
    <nav class="breadcrumb" aria-label="位置"><a href="#/">全部实验</a><span aria-hidden="true">/</span><span>${experiment.number} ${escapeHtml(experiment.title)}</span></nav>

    <header class="exp-head">
      <div class="card-meta"><span class="mono">实验 ${experiment.number}</span><span class="tag">${escapeHtml(experiment.capability)}</span></div>
      <h1>${escapeHtml(experiment.question)}</h1>
      <p class="hero-lead">${escapeHtml(experiment.summary)}</p>
    </header>

    ${renderPrompt(experiment)}

    <section class="results" aria-labelledby="results-heading">
      <div class="results-head">
        <h2 id="results-heading">模型产物 <span class="count">${results.length}</span></h2>
        ${results.length ? `
        <div class="controls">
          ${results.length > 1 ? `
          <div class="segmented" role="group" aria-label="查看方式">
            <a href="${link({ view: null })}" data-replace aria-current="${view === "focus"}">单个</a>
            <a href="${link({ view: "compare" })}" data-replace aria-current="${view === "compare"}">并排</a>
          </div>` : ""}
          ${isPage ? `
          <div class="segmented" role="group" aria-label="预览尺寸">
            ${Object.entries(VIEWPORTS).map(([key, value]) => `
              <a href="${link({ vp: key === "mobile" ? "mobile" : null })}" data-replace aria-current="${viewport === key}" title="按 ${value.width}×${value.height} 渲染后缩放">${value.label}</a>`).join("")}
          </div>` : ""}
        </div>` : ""}
      </div>

      ${!results.length ? `
        <div class="empty-state"><strong>这个实验还没有模型产物</strong><p>Prompt 已经可以阅读，有产物后会出现在这里。</p></div>`
      : view === "compare" ? renderCompare(experiment, viewport, link)
      : renderFocus(experiment, active, viewport, link)}
    </section>

    ${renderMethod(experiment)}
  `;

  app.querySelectorAll(".frame-box").forEach((box) => frameObserver.observe(box));
  bindPrompt(experiment);
}

function renderPrompt(experiment) {
  const long = experiment.prompt.split("\n").length > 8 || experiment.prompt.length > 420;
  return `
    <section class="prompt-card${long ? " is-collapsed" : ""}" aria-labelledby="prompt-heading">
      <div class="prompt-bar">
        <h2 id="prompt-heading">Prompt <span class="mono muted">v${experiment.promptVersion} · ${experiment.prompt.length.toLocaleString()} 字符</span></h2>
        <div class="prompt-actions">
          <button class="button" type="button" data-copy-prompt>复制</button>
          <a class="button ghost" href="${escapeHtml(experiment.promptPath)}" target="_blank" rel="noopener">源文件</a>
        </div>
      </div>
      <pre class="prompt-text" id="prompt-text">${escapeHtml(experiment.prompt)}</pre>
      ${long ? `<button class="prompt-toggle" type="button" aria-expanded="false" aria-controls="prompt-text" data-toggle-prompt>展开全部</button>` : ""}
      <p class="sr-only" role="status" data-prompt-status></p>
    </section>`;
}

function bindPrompt(experiment) {
  const card = app.querySelector(".prompt-card");
  const status = app.querySelector("[data-prompt-status]");
  app.querySelector("[data-copy-prompt]")?.addEventListener("click", async (event) => {
    const button = event.currentTarget;
    try {
      await navigator.clipboard.writeText(experiment.prompt);
      button.textContent = "已复制";
      status.textContent = "Prompt 已复制";
    } catch {
      button.textContent = "复制失败";
      status.textContent = "复制失败，请手动选中文本";
    }
    setTimeout(() => { button.textContent = "复制"; }, 1600);
  });
  app.querySelector("[data-toggle-prompt]")?.addEventListener("click", (event) => {
    const collapsed = card.classList.toggle("is-collapsed");
    event.currentTarget.setAttribute("aria-expanded", String(!collapsed));
    event.currentTarget.textContent = collapsed ? "展开全部" : "收起";
  });
}

function renderModelTabs(experiment, active, link) {
  return `
    <div class="model-tabs" role="tablist" aria-label="选择模型">
      ${experiment.results.map((result) => {
        const selected = result.key === active.key;
        return `
        <a class="model-tab" role="tab" href="${link({ m: result.key })}" data-replace data-key="${escapeHtml(result.key)}"
           aria-selected="${selected}" tabindex="${selected ? 0 : -1}">
          ${vendorDot(result.vendor)}
          <span class="model-tab-name">${escapeHtml(result.label)}</span>
          <span class="score-pill${result.score ? "" : " is-pending"}">${scoreText(result)}</span>
        </a>`;
      }).join("")}
    </div>`;
}

function renderFrame(experiment, result, viewport, { lazy = false } = {}) {
  if (experiment.artifactType === "image") {
    return `<div class="image-box"><img src="${escapeHtml(result.url)}" alt="${escapeHtml(result.label)} 生成的 SVG 原图" ${lazy ? "loading=\"lazy\"" : ""}></div>`;
  }
  const size = VIEWPORTS[viewport];
  return `
    <div class="frame-box is-${viewport}" style="--vw:${size.width};--vh:${size.height}" data-vw="${size.width}" data-vh="${size.height}">
      <iframe src="${escapeHtml(result.url)}" title="${escapeHtml(result.label)} 的原始产物" width="${size.width}" height="${size.height}" ${lazy ? "loading=\"lazy\"" : ""}></iframe>
    </div>`;
}

function fitFrame(box) {
  const width = Number(box.dataset.vw);
  const height = Number(box.dataset.vh);
  const inset = box.classList.contains("is-mobile") ? 32 : 0;
  const scale = Math.min((box.clientWidth - inset) / width, (box.clientHeight - inset) / height);
  box.style.setProperty("--scale", String(scale));
}

function renderFocus(experiment, active, viewport, link) {
  const scored = scoredResults(experiment);
  const rank = active.score ? scored.findIndex((result) => result.key === active.key) + 1 : null;
  return `
    ${renderModelTabs(experiment, active, link)}
    <div class="stage" role="tabpanel" aria-label="${escapeHtml(active.label)}">
      <div class="stage-bar">
        <span class="stage-title">${vendorDot(active.vendor)}${escapeHtml(active.label)}</span>
        <span class="stage-actions">
          ${experiment.artifactType === "page" ? `<span class="mono stage-size">${VIEWPORTS[viewport].width}×${VIEWPORTS[viewport].height}</span>` : ""}
          <button class="stage-button" type="button" data-reload title="重新加载">重新加载</button>
          <a class="stage-button" href="${escapeHtml(active.url)}" target="_blank" rel="noopener">新窗口打开 ↗</a>
        </span>
      </div>
      ${renderFrame(experiment, active, viewport)}
    </div>

    <div class="detail-grid">
      <section class="panel" aria-labelledby="score-heading">
        <h3 id="score-heading">评分</h3>
        ${active.score ? `
          <div class="score-hero">
            <strong>${active.score.total}</strong><span>/ 100</span>
            <span class="rank">本实验第 ${rank} / ${scored.length}</span>
          </div>
          <ul class="meters">
            ${active.score.dimensions.map((dimension) => `
              <li>
                <div class="meter-label"><span>${escapeHtml(dimension.name)}</span><span class="mono">${dimension.value} / ${dimension.max}</span></div>
                <div class="meter" role="img" aria-label="${escapeHtml(dimension.name)} ${dimension.value} / ${dimension.max}"><span style="--value:${(dimension.value / dimension.max) * 100}"></span></div>
              </li>`).join("")}
          </ul>`
        : `<p class="pending-note"><strong>待评估</strong>产物已经保存，但还没有正式评分。这不代表失败，也不是零分。</p>`}
      </section>

      <section class="panel" aria-labelledby="review-heading">
        <h3 id="review-heading">点评</h3>
        ${active.review ? `
          <div class="review">
            <h4 class="review-good">优点</h4>
            <ul>${active.review.strengths.map((item) => `<li>${inlineMarkdown(item)}</li>`).join("")}</ul>
            ${active.review.weaknesses.length ? `
            <h4 class="review-bad">不足</h4>
            <ul>${active.review.weaknesses.map((item) => `<li>${inlineMarkdown(item)}</li>`).join("")}</ul>` : ""}
          </div>`
        : `<p class="muted">还没有点评。</p>`}
      </section>

      <details class="panel run-panel">
        <summary><h3>运行记录</h3><span class="muted">run.yaml</span></summary>
        <dl class="run-facts">
          ${[
            ["Prompt 版本", `v${active.run.prompt_version}`],
            ["调用渠道", active.run.provider],
            ["模型", active.run.model],
            ["运行模式", active.run.mode],
            ["生成时间", active.run.generated_at],
            ["入口文件", active.run.entrypoint]
          ].map(([term, value]) => `<div><dt>${term}</dt><dd class="mono${value === "unknown" ? " muted" : ""}">${escapeHtml(value)}</dd></div>`).join("")}
        </dl>
        <p class="muted small">unknown 表示当时没有可靠记录，不是默认值。</p>
      </details>
    </div>`;
}

function renderCompare(experiment, viewport, link) {
  return `
    <div class="compare-grid${experiment.artifactType === "image" ? " is-image" : ""}${viewport === "mobile" ? " is-mobile" : ""}">
      ${experiment.results.map((result) => `
        <article class="compare-card">
          <header>
            <span class="stage-title">${vendorDot(result.vendor)}${escapeHtml(result.label)}</span>
            <span class="score-pill${result.score ? "" : " is-pending"}">${scoreText(result)}</span>
          </header>
          ${renderFrame(experiment, result, viewport, { lazy: true })}
          <footer>
            <a href="${link({ m: result.key, view: null })}" data-replace>查看详情</a>
            <a href="${escapeHtml(result.url)}" target="_blank" rel="noopener">新窗口打开 ↗</a>
          </footer>
        </article>`).join("")}
    </div>`;
}

function renderMethod(experiment) {
  const evaluation = experiment.evaluation;
  return `
    <section class="section method" aria-labelledby="method-heading">
      <div class="section-head">
        <h2 id="method-heading">怎么评</h2>
        <p>${evaluation
          ? [evaluation.method, evaluation.environment, evaluation.date !== "unknown" && `评测于 ${evaluation.date}`].filter((item) => item && item !== "unknown").map(escapeHtml).join(" · ")
          : "这个实验还没有正式评测，下面是观察时建议关注的方面。"}</p>
      </div>
      <div class="method-grid">
        <div class="panel">
          <h3>看效果时关注</h3>
          <ul class="check-list">${experiment.focus.map((item) => `<li>${escapeHtml(item)}</li>`).join("")}</ul>
        </div>
        <div class="panel">
          <h3>评分维度</h3>
          ${evaluation ? `
            <ul class="dimension-list">
              ${evaluation.dimensions.map((dimension) => `
                <li><div><strong>${escapeHtml(dimension.name)}</strong><p>${escapeHtml(dimension.focus)}</p></div><span class="mono">${dimension.weight}%</span></li>`).join("")}
            </ul>
            <a class="text-link" href="${escapeHtml(experiment.evaluationPath)}" target="_blank" rel="noopener">完整评测记录 ↗</a>`
          : `<p class="muted">尚无评分维度。</p>`}
        </div>
      </div>
      ${evaluation?.conclusion.length ? `
        <div class="panel conclusion">
          <h3>评测结论</h3>
          ${evaluation.conclusion.map((paragraph) => `<p>${inlineMarkdown(paragraph)}</p>`).join("")}
        </div>` : ""}
    </section>`;
}

function inlineMarkdown(text) {
  return escapeHtml(text)
    .replace(/`([^`]+)`/g, "<code>$1</code>")
    .replace(/\*\*([^*]+)\*\*/g, "<strong>$1</strong>");
}

/* ---------- Router ---------- */

function render() {
  if (!lab) return;
  frameObserver.disconnect();
  const { path, params } = parseRoute();
  const experiment = lab.experiments.find((item) => item.id === path);
  const page = experiment ? experiment.id : "home";

  if (experiment) renderExperiment(experiment, params);
  else renderHome(params);

  document.querySelectorAll("[data-nav]").forEach((link) => {
    const current = !experiment && (link.dataset.nav === "matrix") === (params.get("section") === "matrix");
    link.toggleAttribute("aria-current", current);
  });

  if (page !== lastPage) {
    if (lastPage !== null && params.get("section") !== "matrix") {
      window.scrollTo(0, 0);
      app.focus({ preventScroll: true });
    }
    lastPage = page;
  }
  if (pendingFocus) {
    app.querySelector(pendingFocus)?.focus();
    pendingFocus = null;
  }
}

app.addEventListener("click", (event) => {
  const link = event.target.closest("a[data-replace]");
  if (link && !event.metaKey && !event.ctrlKey && !event.shiftKey) {
    event.preventDefault();
    if (link.matches(".model-tab")) pendingFocus = `.model-tab[data-key="${CSS.escape(link.dataset.key)}"]`;
    navigate(link.getAttribute("href"), { replace: true });
    return;
  }
  if (event.target.closest("[data-reload]")) {
    const frame = app.querySelector(".stage iframe, .stage img");
    if (frame) frame.src = frame.src;
  }
});

app.addEventListener("keydown", (event) => {
  const tab = event.target.closest(".model-tab");
  if (!tab || !["ArrowLeft", "ArrowRight", "Home", "End"].includes(event.key)) return;
  const tabs = [...app.querySelectorAll(".model-tab")];
  const index = tabs.indexOf(tab);
  const next = event.key === "Home" ? 0
    : event.key === "End" ? tabs.length - 1
    : (index + (event.key === "ArrowRight" ? 1 : -1) + tabs.length) % tabs.length;
  event.preventDefault();
  tabs[next].click();
});

document.querySelector("#theme-toggle").addEventListener("click", () => {
  const root = document.documentElement;
  const current = root.dataset.theme ?? (matchMedia("(prefers-color-scheme: dark)").matches ? "dark" : "light");
  const next = current === "dark" ? "light" : "dark";
  root.dataset.theme = next;
  try { localStorage.setItem("lab-theme", next); } catch {}
});

window.addEventListener("hashchange", render);

fetch("data/lab.json")
  .then((response) => {
    if (!response.ok) throw new Error(`HTTP ${response.status}`);
    return response.json();
  })
  .then((data) => {
    lab = data;
    render();
  })
  .catch((error) => {
    app.innerHTML = `<div class="empty-state"><strong>数据加载失败</strong><p>请通过 HTTP 服务打开本页（例如 <code>python -m http.server</code>）。${escapeHtml(error.message)}</p></div>`;
  });
