const $=id=>document.getElementById(id),experience=$('experience'),world=$('world'),rocket=$('rocketWrap'),ground=$('ground'),complex=$('complex'),launchButton=$('launchButton'),replayButton=$('replayButton'),countdown=$('countdown'),countNumber=countdown.querySelector('strong'),statusPanel=$('statusPanel'),statusTitle=$('statusTitle'),statusText=$('statusText'),statusKicker=$('statusKicker'),progressBar=$('timelineProgress'),altitude=$('altitude'),velocity=$('velocity'),missionTime=$('missionTime'),canvas=$('fxCanvas'),ctx=canvas.getContext('2d');
let dpr=1,particles=[],embers=[],phase='idle',launchStart=0,token=0,audioContext,engineGain;
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),easeIn=v=>v*v*v,ease=v=>v<.5?4*v*v*v:1-Math.pow(-2*v+2,3)/2,sleep=ms=>new Promise(r=>setTimeout(r,ms));
function resize(){dpr=Math.min(devicePixelRatio||1,2);canvas.width=innerWidth*dpr;canvas.height=innerHeight*dpr;canvas.style.width=innerWidth+'px';canvas.style.height=innerHeight+'px';ctx.setTransform(dpr,0,0,dpr,0,0)}
function nozzle(){const r=rocket.getBoundingClientRect();return{x:r.left+r.width/2,y:r.top+r.height*.965,w:r.width}}
function emit(power,airborne=false){const n=nozzle(),amount=Math.ceil(power*(airborne?2.2:5.4));for(let i=0;i<amount;i++)particles.push({x:n.x+(Math.random()-.5)*n.w*(airborne?.36:1.1),y:n.y+Math.random()*12,vx:(Math.random()-.5)*(airborne?1.7:5.4)*power,vy:airborne?2.5+Math.random()*5.5:-.1-Math.random()*1.1,size:(airborne?8:13)+Math.random()*(airborne?16:27),grow:airborne?.35:.75+Math.random()*.7,life:1,decay:airborne?.017+Math.random()*.015:.006+Math.random()*.008,warm:Math.random()<(airborne?.28:.16)});for(let i=0;i<Math.ceil(power*1.8);i++)embers.push({x:n.x+(Math.random()-.5)*n.w*.45,y:n.y+Math.random()*10,vx:(Math.random()-.5)*3.8,vy:3+Math.random()*8,life:1,decay:.025+Math.random()*.035,size:1+Math.random()*2.8})}
function draw(){ctx.clearRect(0,0,innerWidth,innerHeight);particles.forEach(p=>{p.x+=p.vx;p.y+=p.vy;p.vx*=.992;p.vy+=phase==='ascent'?.012:-.006;p.size+=p.grow;p.life-=p.decay;const a=Math.max(0,p.life)*.44,g=ctx.createRadialGradient(p.x,p.y,0,p.x,p.y,p.size);g.addColorStop(0,p.warm?`rgba(255,181,90,${a*.7})`:`rgba(228,231,226,${a})`);g.addColorStop(.38,`rgba(151,155,151,${a*.74})`);g.addColorStop(1,'rgba(68,72,71,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()});particles=particles.filter(p=>p.life>0&&p.y<innerHeight+150);ctx.globalCompositeOperation='lighter';embers.forEach(e=>{e.x+=e.vx;e.y+=e.vy;e.vy+=.08;e.life-=e.decay;ctx.fillStyle=`rgba(255,${90+e.life*140},34,${Math.max(0,e.life)})`;ctx.beginPath();ctx.arc(e.x,e.y,e.size*Math.max(0,e.life),0,Math.PI*2);ctx.fill()});embers=embers.filter(e=>e.life>0);ctx.globalCompositeOperation='source-over'}
function initAudio(){if(audioContext)return;audioContext=new(window.AudioContext||window.webkitAudioContext)();engineGain=audioContext.createGain();engineGain.gain.value=0;engineGain.connect(audioContext.destination);const size=audioContext.sampleRate*2,buffer=audioContext.createBuffer(1,size,audioContext.sampleRate),data=buffer.getChannelData(0);for(let i=0;i<size;i++)data[i]=Math.random()*2-1;const noise=audioContext.createBufferSource(),filter=audioContext.createBiquadFilter();noise.buffer=buffer;noise.loop=true;filter.type='lowpass';filter.frequency.value=165;filter.Q.value=1.2;noise.connect(filter).connect(engineGain);noise.start();[31,46].forEach((f,i)=>{const o=audioContext.createOscillator(),g=audioContext.createGain();o.type=i?'triangle':'sine';o.frequency.value=f;g.gain.value=i?.085:.13;o.connect(g).connect(engineGain);o.start()})}
function volume(v,r=.5){if(!engineGain)return;const now=audioContext.currentTime;engineGain.gain.cancelScheduledValues(now);engineGain.gain.setValueAtTime(engineGain.gain.value,now);engineGain.gain.linearRampToValueAtTime(v,now+r)}
async function runCountdown(current){countdown.style.opacity=1;for(const value of ['3','2','1']){if(current!==token)return false;countNumber.textContent=value;countNumber.animate([{opacity:0,transform:'scale(1.5)'},{opacity:1,transform:'scale(1)',offset:.25},{opacity:1,transform:'scale(.94)',offset:.72},{opacity:0,transform:'scale(.72)'}],{duration:900,easing:'cubic-bezier(.2,.7,.3,1)'});await sleep(900)}countdown.style.opacity=0;return current===token}
function telemetry(elapsed,p){const alt=Math.pow(p,2.15)*126,speed=Math.round(Math.pow(p,.76)*28100),seconds=Math.floor(elapsed/1000);altitude.textContent=alt<10?alt.toFixed(1):alt.toFixed(0);velocity.textContent=speed.toLocaleString('zh-CN');missionTime.textContent=`T+${String(Math.floor(seconds/60)).padStart(2,'0')}:${String(seconds%60).padStart(2,'0')}`;progressBar.style.width=p*100+'%'}
function loop(now){draw();if(phase==='ignition'){emit(1.25);const shake=1.5+Math.random()*2.2;rocket.style.transform=`translate(${(Math.random()-.5)*shake}px,${(Math.random()-.5)*shake}px)`}if(phase==='ascent'){const elapsed=now-launchStart,p=clamp(elapsed/15000,0,1),early=clamp(p/.32,0,1),later=clamp((p-.22)/.78,0,1),y=-easeIn(early)*innerHeight*.31-ease(later)*innerHeight*.08,scale=1-later*.31,drift=Math.sin(p*Math.PI*1.4)*innerWidth*.018+later*innerWidth*.075,tilt=later*4.2,vibration=(1-p)*1.5,drop=easeIn(early)*innerHeight*.8+later*innerHeight*.95;rocket.style.transform=`translate(${drift+(Math.random()-.5)*vibration}px,${y}px) rotate(${tilt}deg) scale(${scale})`;ground.style.transform=`translateY(${drop}px) scale(${1+early*.3})`;complex.style.transform=`translateY(${drop}px) scale(${1+early*.28})`;emit(1.2-p*.45,true);telemetry(elapsed,p);if(p>.46&&!experience.classList.contains('space-mode')){experience.classList.add('space-mode');statusKicker.textContent='EXOATMOSPHERIC FLIGHT';statusTitle.textContent='穿越大气层';statusText.textContent='速度与轨迹正常，飞行器正在接近卡门线。';volume(.15,3.5)}if(p>.76)world.style.filter=`brightness(${1-(p-.76)*.5})`;if(p>=1)finish()}requestAnimationFrame(loop)}
async function launch(){if(phase!=='idle')return;const current=++token;phase='countdown';launchButton.disabled=true;launchButton.textContent='发射序列启动';statusKicker.textContent='AUTOMATED LAUNCH SEQUENCE';statusTitle.textContent='发射倒计时';statusText.textContent='飞行计算机接管控制，推进剂增压，点火系统就绪。';initAudio();if(audioContext.state==='suspended')await audioContext.resume();if(!await runCountdown(current))return;phase='ignition';experience.classList.add('ignition');volume(.42,.7);statusKicker.textContent='MAIN ENGINE IGNITION';statusTitle.textContent='发动机点火';statusText.textContent='推力建立中，三台主发动机燃烧稳定。';await sleep(2300);if(current!==token)return;phase='ascent';launchStart=performance.now();experience.classList.add('liftoff');volume(.5,.5);statusKicker.textContent='LIFTOFF CONFIRMED';statusTitle.textContent='离塔 · 开始上升';statusText.textContent='推重比正常，姿态稳定，逐星一号正加速驶向太空。'}
function finish(){if(phase==='complete')return;phase='complete';experience.classList.add('complete');volume(0,2.2);statusPanel.style.opacity=0;rocket.animate([{opacity:1},{opacity:.88,offset:.7},{opacity:.72}],{duration:1800,fill:'forwards'})}
function reset(){token++;phase='idle';particles=[];embers=[];experience.className='experience';world.style.filter='';ground.style.transform='';complex.style.transform='';rocket.style.transform='';rocket.getAnimations().forEach(a=>a.cancel());rocket.style.opacity='';statusPanel.style.opacity='';countdown.style.opacity=0;launchButton.disabled=false;launchButton.textContent='点火发射';statusKicker.textContent='ALL SYSTEMS NOMINAL';statusTitle.textContent='逐星一号 · 等待发射';statusText.textContent='发动机预冷完成，导航与遥测链路正常。点击按钮，开启从地面到星海的完整发射任务。';altitude.textContent='0.0';velocity.textContent='0';missionTime.textContent='T+00:00';progressBar.style.width=0;volume(0,.15)}
launchButton.addEventListener('click',launch);replayButton.addEventListener('click',reset);addEventListener('resize',resize);resize();requestAnimationFrame(loop);

